services:
  - type: web
    name: heart-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn heart_api.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: heart_api.settings
      - key: PYTHON_VERSION
        value: 3.10
